### ISSUE TITLE
Feature Request - Sort Discovered Universes

### ISSUE THREAD

**Issue by EVeik** [docsteer/sacnview#177]
Was looking for sACN sources on the line and checked out Discovered Universes.  Below is a screenshot.  As you can see, the universes are not in numeric order.  I am assuming they are listed in the order of discovery, which makes sense.  Would be nice to be able to right click and sort in some manner.

![sacn resort order of discovery universes](https://user-images.githubusercontent.com/30304657/50232376-69596000-0376-11e9-818d-2f897318010a.jpg)

Thanks.

**Comment by docsteer** [comment]
@EVeik I think you're running beta 2 - I released beta 3 on Sunday, and that should sort these alphabetically

**Comment by EVeik** [comment]
I can confirm that I was in beta 2 when those screenshots were taken.  I am doing some mockup and beta 3 doesn’t appear to see any discovered universes.

[cid:image001.png@01D4991A.76E58620]

[cid:image002.png@01D4991A.76E58620]
Eric Veik

**Comment by marcusbirkin** [comment]
@EVeik Can you confirm if this is resolved in v2.1?

**Comment by EVeik** [comment]
I will take a look shortly.

**Comment by EVeik** [comment]
Looks like it is still present in 2.1.0 release.  Here is a screenshot.  Source is another computer running 2.1.0 release.

[cid:image001.png@01D58383.A394A580]
